# Generated by Django 4.2.4 on 2023-08-31 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0006_rating"),
    ]

    operations = [
        migrations.RenameField(
            model_name="resourcetag",
            old_name="Resources_id",
            new_name="resources",
        ),
        migrations.RenameField(
            model_name="resourcetag",
            old_name="tag_id",
            new_name="tag",
        ),
        migrations.AddConstraint(
            model_name="resourcetag",
            constraint=models.UniqueConstraint(
                condition=models.Q(("tag__isnull", False)),
                fields=("resources", "tag"),
                name="resource_tag_unique",
            ),
        ),
    ]
