# Generated by Django 4.2.4 on 2023-10-05 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0008_review_rating_review_resource"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ResourceTag",
            new_name="ResourcesTag",
        ),
        migrations.RemoveConstraint(
            model_name="resourcestag",
            name="resource_tag_unique",
        ),
        migrations.RenameField(
            model_name="resourcestag",
            old_name="resources",
            new_name="resources_id",
        ),
        migrations.RenameField(
            model_name="resourcestag",
            old_name="tag",
            new_name="tag_id",
        ),
        migrations.RemoveField(
            model_name="review",
            name="rating",
        ),
        migrations.RemoveField(
            model_name="review",
            name="resource",
        ),
        migrations.AddConstraint(
            model_name="resourcestag",
            constraint=models.UniqueConstraint(
                models.F("resources_id"),
                models.F("tag_id"),
                name="resource_tag_unique",
                violation_error_message="Tag already exist for resource",
            ),
        ),
    ]
